Session 3 - Sector-Wise Domestic Savings (At Current Prices)

Dataset: RBI Handbook of Statistics on Indian States
Goal: Learn how to inspect, filter, sort and summarise a real dataset using Pandas.

.sector wise domestic saving 
Non-financial corporations 
financial corporations
general government 
household sector

In [2]:
import pandas as pd

In [10]:
df = pd.read_csv(r'C:\Users\abhis\Downloads\data acj\UDISE_2023-24_Table_2.1.csv')

In [11]:
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("-", "_")
df.columns = df.columns.str.lower()
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [12]:
df.head()

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
0,1,India,1471891,248045828,9807600,50.00,29.40,9.80,10.80,48.70,25.40,14.90,10.90,24.00,28.60,16.20,31.10
1,2,Andaman and Nicobar Islands,412,72119,5750,50.70,19.20,13.10,17.00,46.10,23.60,15.90,14.40,17.30,16.90,17.50,48.30
2,3,Andhra Pradesh,61373,8741885,338293,61.50,13.50,18.90,6.10,46.10,25.70,16.50,11.60,28.60,14.00,42.70,14.70
3,4,Arunachal Pradesh,3490,323717,24700,48.60,36.80,9.50,5.20,53.70,24.00,13.40,8.90,19.10,42.60,20.60,17.60
4,5,Assam,56630,6922533,342199,66.20,16.70,12.50,4.70,53.40,25.10,14.30,7.20,32.60,20.50,29.10,17.80

In [13]:
df.tail(5)

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
32,33,Telangana,42901,7293644,341460,47.90,17.40,27.00,7.70,47.80,25.20,15.30,11.80,14.30,16.00,52.70,16.90
33,34,Tripura,4923,689408,37661,50.20,25.30,13.60,10.80,48.40,25.20,14.60,11.80,20.50,20.00,21.80,37.60
34,35,Uttar Pradesh,255087,41662794,1538479,52.30,34.00,4.70,9.00,49.40,25.40,13.70,11.50,36.60,34.10,5.60,23.70
35,36,Uttarakhand,22551,2372400,130741,57.30,24.40,6.20,12.00,47.70,24.20,15.00,13.10,23.70,25.20,8.80,42.30
36,37,West Bengal,93945,18015525,576557,79.30,9.20,3.50,8.10,47.00,24.50,17.00,11.50,52.20,6.70,6.50,34.60